#!/bin/bash
# Void Display Manager Main Script
# Location: src/void-dm.sh

# Configuration
CONFIG_DIR="$HOME/.config/void-dm"
GLOBAL_CONFIG="/etc/void-dm"
SESSION_LIST="$CONFIG_DIR/sessions"
DIALOG_HEIGHT=15
DIALOG_WIDTH=50
LOG_FILE="/var/log/void-dm.log"

# Ensure we're running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# Setup logging
exec 1> >(tee -a "$LOG_FILE")
exec 2>&1
echo "Starting Void Display Manager at $(date)"

# Create user config if it doesn't exist
setup_config() {
    if [ ! -d "$CONFIG_DIR" ]; then
        mkdir -p "$CONFIG_DIR"
        cp "$GLOBAL_CONFIG/sessions.default" "$SESSION_LIST"
        chmod 644 "$SESSION_LIST"
    fi
}

# Function to get available sessions
get_sessions() {
    local sessions=""
    while IFS=: read -r name path; do
        if [ -x "$path" ]; then
            sessions="$sessions $name $path"
        fi
    done < "$SESSION_LIST"
    echo $sessions
}

# Function to start X session
start_session() {
    local username="$1"
    local session_path="$2"
    
    if [ -x "$session_path" ]; then
        # Create .xinitrc
        local user_home=$(getent passwd "$username" | cut -d: -f6)
        cat > "$user_home/.xinitrc" << EOF
#!/bin/sh
# Auto-generated by Void Display Manager
if [ -f "\$HOME/.Xresources" ]; then
    xrdb -merge "\$HOME/.Xresources"
fi

if [ -d "\$HOME/.xinitrc.d" ]; then
    for f in "\$HOME/.xinitrc.d/"*; do
        [ -x "\$f" ] && . "\$f"
    done
fi

exec $session_path
EOF
        chown "$username:$(id -gn "$username")" "$user_home/.xinitrc"
        chmod +x "$user_home/.xinitrc"
        
        # Start X session
        su -l "$username" -c "startx"
    else
        dialog --title "Error" \
               --msgbox "Session executable not found: $session_path" \
               8 40
    fi
}

# Main loop
setup_config

while true; do
    # Get username
    USERNAME=$(dialog --stdout \
                     --no-cancel \
                     --title "Void Linux Display Manager" \
                     --inputbox "Username:" \
                     $DIALOG_HEIGHT $DIALOG_WIDTH)
    
    # Get password
    PASSWORD=$(dialog --stdout \
                     --no-cancel \
                     --title "Void Linux Display Manager" \
                     --passwordbox "Password:" \
                     $DIALOG_HEIGHT $DIALOG_WIDTH)
    
    # Verify credentials
    if echo "$PASSWORD" | su -c "exit" - "$USERNAME" >/dev/null 2>&1; then
        # Select session
        SESSION=$(dialog --stdout \
                        --title "Select Session" \
                        --menu "Choose desktop environment:" \
                        $DIALOG_HEIGHT $DIALOG_WIDTH 5 \
                        $(get_sessions))
        
        if [ $? -eq 0 ]; then
            # Get session path
            SESSION_PATH=$(grep "^$SESSION:" "$SESSION_LIST" | cut -d: -f2)
            
            # Clear screen and start session
            clear
            echo "Starting session $SESSION for user $USERNAME..."
            start_session "$USERNAME" "$SESSION_PATH"
        fi
    else
        dialog --title "Error" \
               --msgbox "Invalid username or password" \
               8 40
    fi
done